/youbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: youbot__arm_joint_0
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: youbot__arm_joint_1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: youbot__arm_joint_2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: youbot__arm_joint_3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: youbot__arm_joint_4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: youbot__arm_joint_5
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Velocity Controllers ---------------------------------------
  # wheel_bl_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: youbot__wheel_joint_bl
  #   pid: {p: 500.0, i: 0.01, d: 10.0}
  # wheel_br_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: youbot__wheel_joint_br
  #   pid: {p: 500.0, i: 0.01, d: 10.0}
  # wheel_fl_velocity_controller:
  #   joint: youbot__wheel_joint_fl
  #   type: effort_controllers/JointVelocityController
  #   pid: {p: 500.0, i: 0.01, d: 10.0}
  # wheel_fr_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: youbot__wheel_joint_fr
  #   pid: {p: 500.0, i: 0.01, d: 10.0}
